'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Database1Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Database1Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property payments() As DbSet(Of payment)
    Public Overridable Property reservations() As DbSet(Of reservation)
    Public Overridable Property roomTypes() As DbSet(Of roomType)
    Public Overridable Property services() As DbSet(Of service)
    Public Overridable Property units() As DbSet(Of unit)
    Public Overridable Property Users() As DbSet(Of User)
    Public Overridable Property billings() As DbSet(Of billing)
    Public Overridable Property service_order() As DbSet(Of service_order)

End Class
