'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class payment
    Public Property Id As Long
    Public Property userid As Integer
    Public Property [date] As Date
    Public Property method As String
    Public Property amount As Integer

    Public Overridable Property User As User

End Class
