'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class reservation
    Public Property Id As Integer
    Public Property checkin As Nullable(Of Date)
    Public Property checkout As Nullable(Of Date)
    Public Property userid As Integer
    Public Property roomno As Integer
    Public Property ischeckedin As String
    Public Property bookingtime As Date
    Public Property ispaid As String

    Public Overridable Property unit As unit
    Public Overridable Property User As User

End Class
