'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class roomType
    Public Property Id As Integer
    Public Property name As String
    Public Property rimage As Byte()
    Public Property minguest As Integer
    Public Property maxguest As Integer
    Public Property price As Double
    Public Property objtype As String

    Public Overridable Property units As ICollection(Of unit) = New HashSet(Of unit)

End Class
