'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class service
    Public Property id As Integer
    Public Property name As String
    Public Property price As Integer

    Public Overridable Property service_order As ICollection(Of service_order) = New HashSet(Of service_order)

End Class
