'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class unit
    Public Property roomno As Integer
    Public Property roomtype As Integer
    Public Property [date] As Nullable(Of Date)
    Public Property minguest As Integer
    Public Property maxguest As Integer
    Public Property isoccuppied As String

    Public Overridable Property reservations As ICollection(Of reservation) = New HashSet(Of reservation)
    Public Overridable Property roomType1 As roomType
    Public Overridable Property service_order As ICollection(Of service_order) = New HashSet(Of service_order)

End Class
