'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class User
    Public Property Id As Integer
    Public Property Name As String
    Public Property Email As String
    Public Property Phone As Long
    Public Property Password As String
    Public Property isbooked As String

    Public Overridable Property payments As ICollection(Of payment) = New HashSet(Of payment)
    Public Overridable Property reservations As ICollection(Of reservation) = New HashSet(Of reservation)
    Public Overridable Property billings As ICollection(Of billing) = New HashSet(Of billing)

End Class
